Update git-pushf
Add more "main branch" names

diff --git a/git-pushf b/git-pushf
--- a/git-pushf
+++ b/git-pushf
@@ -39,6 +39,18 @@ then
     exit 3
 fi
 
+if [[ "$BRANCH_NAME" == "develop" ]]
+then
+    echo "error: force-updating develop is not allowed"
+    exit 3
+fi
+
+if [[ "$BRANCH_NAME" == "main" ]]
+then
+    echo "error: force-updating main is not allowed"
+    exit 3
+fi
+
 if shouldAssertUsernameInBranch;
 then
     GIT_USERNAME="`getExgitUsername`"
